//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisOfertasFinal.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EntitiesOfertas : DbContext
    {
        public EntitiesOfertas()
            : base("name=EntitiesOfertas")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CATGORIAPRODUCTO> CATGORIAPRODUCTO { get; set; }
        public DbSet<COMUNA> COMUNA { get; set; }
        public DbSet<EMPRESA> EMPRESA { get; set; }
        public DbSet<MARCA> MARCA { get; set; }
        public DbSet<OFERTA> OFERTA { get; set; }
        public DbSet<PRIORIDAD> PRIORIDAD { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<RUBROPRODUCTO> RUBROPRODUCTO { get; set; }
        public DbSet<TICKETDESCUENTO> TICKETDESCUENTO { get; set; }
        public DbSet<TIENDA> TIENDA { get; set; }
        public DbSet<TIPOUSUARIO> TIPOUSUARIO { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VALORACION> VALORACION { get; set; }
    
        public virtual int insertarUsuario(Nullable<decimal> p_ID_USUARIO, string p_DIRECCION_USUARIO, string p_APEPA_USUARIO, string p_RUT_USUARIO, string p_APEMA_USUARIO, Nullable<decimal> p_TICKETDESCUENTO_ID_TICKET, string p_PASSWORD_USUARIO, Nullable<decimal> p_PRIORIDAD_ID_VISITA, Nullable<decimal> p_COMUNA_ID_COMUNA, string p_NOMBRE_USUARIO, Nullable<decimal> p_TIPOUSUARIO_ID_TIPOUSUARIO, Nullable<decimal> p_TIENDA_ID_TIENDA, string p_CORREO_USUARIO, Nullable<decimal> p_PUNTOS_USUARIO, string p_TELEFONO_USUARIO)
        {
            var p_ID_USUARIOParameter = p_ID_USUARIO.HasValue ?
                new ObjectParameter("P_ID_USUARIO", p_ID_USUARIO) :
                new ObjectParameter("P_ID_USUARIO", typeof(decimal));
    
            var p_DIRECCION_USUARIOParameter = p_DIRECCION_USUARIO != null ?
                new ObjectParameter("P_DIRECCION_USUARIO", p_DIRECCION_USUARIO) :
                new ObjectParameter("P_DIRECCION_USUARIO", typeof(string));
    
            var p_APEPA_USUARIOParameter = p_APEPA_USUARIO != null ?
                new ObjectParameter("P_APEPA_USUARIO", p_APEPA_USUARIO) :
                new ObjectParameter("P_APEPA_USUARIO", typeof(string));
    
            var p_RUT_USUARIOParameter = p_RUT_USUARIO != null ?
                new ObjectParameter("P_RUT_USUARIO", p_RUT_USUARIO) :
                new ObjectParameter("P_RUT_USUARIO", typeof(string));
    
            var p_APEMA_USUARIOParameter = p_APEMA_USUARIO != null ?
                new ObjectParameter("P_APEMA_USUARIO", p_APEMA_USUARIO) :
                new ObjectParameter("P_APEMA_USUARIO", typeof(string));
    
            var p_TICKETDESCUENTO_ID_TICKETParameter = p_TICKETDESCUENTO_ID_TICKET.HasValue ?
                new ObjectParameter("P_TICKETDESCUENTO_ID_TICKET", p_TICKETDESCUENTO_ID_TICKET) :
                new ObjectParameter("P_TICKETDESCUENTO_ID_TICKET", typeof(decimal));
    
            var p_PASSWORD_USUARIOParameter = p_PASSWORD_USUARIO != null ?
                new ObjectParameter("P_PASSWORD_USUARIO", p_PASSWORD_USUARIO) :
                new ObjectParameter("P_PASSWORD_USUARIO", typeof(string));
    
            var p_PRIORIDAD_ID_VISITAParameter = p_PRIORIDAD_ID_VISITA.HasValue ?
                new ObjectParameter("P_PRIORIDAD_ID_VISITA", p_PRIORIDAD_ID_VISITA) :
                new ObjectParameter("P_PRIORIDAD_ID_VISITA", typeof(decimal));
    
            var p_COMUNA_ID_COMUNAParameter = p_COMUNA_ID_COMUNA.HasValue ?
                new ObjectParameter("P_COMUNA_ID_COMUNA", p_COMUNA_ID_COMUNA) :
                new ObjectParameter("P_COMUNA_ID_COMUNA", typeof(decimal));
    
            var p_NOMBRE_USUARIOParameter = p_NOMBRE_USUARIO != null ?
                new ObjectParameter("P_NOMBRE_USUARIO", p_NOMBRE_USUARIO) :
                new ObjectParameter("P_NOMBRE_USUARIO", typeof(string));
    
            var p_TIPOUSUARIO_ID_TIPOUSUARIOParameter = p_TIPOUSUARIO_ID_TIPOUSUARIO.HasValue ?
                new ObjectParameter("P_TIPOUSUARIO_ID_TIPOUSUARIO", p_TIPOUSUARIO_ID_TIPOUSUARIO) :
                new ObjectParameter("P_TIPOUSUARIO_ID_TIPOUSUARIO", typeof(decimal));
    
            var p_TIENDA_ID_TIENDAParameter = p_TIENDA_ID_TIENDA.HasValue ?
                new ObjectParameter("P_TIENDA_ID_TIENDA", p_TIENDA_ID_TIENDA) :
                new ObjectParameter("P_TIENDA_ID_TIENDA", typeof(decimal));
    
            var p_CORREO_USUARIOParameter = p_CORREO_USUARIO != null ?
                new ObjectParameter("P_CORREO_USUARIO", p_CORREO_USUARIO) :
                new ObjectParameter("P_CORREO_USUARIO", typeof(string));
    
            var p_PUNTOS_USUARIOParameter = p_PUNTOS_USUARIO.HasValue ?
                new ObjectParameter("P_PUNTOS_USUARIO", p_PUNTOS_USUARIO) :
                new ObjectParameter("P_PUNTOS_USUARIO", typeof(decimal));
    
            var p_TELEFONO_USUARIOParameter = p_TELEFONO_USUARIO != null ?
                new ObjectParameter("P_TELEFONO_USUARIO", p_TELEFONO_USUARIO) :
                new ObjectParameter("P_TELEFONO_USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertarUsuario", p_ID_USUARIOParameter, p_DIRECCION_USUARIOParameter, p_APEPA_USUARIOParameter, p_RUT_USUARIOParameter, p_APEMA_USUARIOParameter, p_TICKETDESCUENTO_ID_TICKETParameter, p_PASSWORD_USUARIOParameter, p_PRIORIDAD_ID_VISITAParameter, p_COMUNA_ID_COMUNAParameter, p_NOMBRE_USUARIOParameter, p_TIPOUSUARIO_ID_TIPOUSUARIOParameter, p_TIENDA_ID_TIENDAParameter, p_CORREO_USUARIOParameter, p_PUNTOS_USUARIOParameter, p_TELEFONO_USUARIOParameter);
        }
    }
}
