//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisOfertasFinal.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.PRIORIDAD = new HashSet<PRIORIDAD>();
            this.TICKETDESCUENTO = new HashSet<TICKETDESCUENTO>();
            this.TIENDA = new HashSet<TIENDA>();
            this.VALORACION = new HashSet<VALORACION>();
        }
    
        public string RUT_USUARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string APEPA_USUARIO { get; set; }
        public string APEMA_USUARIO { get; set; }
        public string CORREO_USUARIO { get; set; }
        public string DIRECCION_USUARIO { get; set; }
        public string TELEFONO_USUARIO { get; set; }
        public string PASSWORD_USUARIO { get; set; }
        public string CORREOACTIVO { get; set; }
        public decimal PUNTOS_USUARIO { get; set; }
        public decimal ID_TIPOUSUARIO { get; set; }
        public decimal ID_COMUNA { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual ICollection<PRIORIDAD> PRIORIDAD { get; set; }
        public virtual ICollection<TICKETDESCUENTO> TICKETDESCUENTO { get; set; }
        public virtual ICollection<TIENDA> TIENDA { get; set; }
        public virtual TIPOUSUARIO TIPOUSUARIO { get; set; }
        public virtual ICollection<VALORACION> VALORACION { get; set; }
    }
}
